export const SET_LOCALES = "SET_LOCALES";
export const SET_LOCALE = "SET_LOCALE";
export const SET_FULL_DATA = "SET_FULL_DATA";
export const SET_DATA_MATCH_LOCALE = "SET_DATA_MATCH_LOCALE";
export const SET_SHOW_SIDEBAR = "SET_SHOW_SIDEBAR";
export const SET_CATEGORIES_FOUND = "SET_CATEGORIES_FOUND";
export const SET_SEARCHING = "SET_SEARCHING";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_CURRENT_SLUG = "SET_CURRENT_SLUG";
export const SET_ALL_POSTS = "SET_ALL_POSTS";
export const SET_CURRENT_POSTS = "SET_CURRENT_POSTS";
export const SET_LOADED = "SET_LOADED";


